server:
  port: 8080

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/calorie_db
    username: alexei
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop